<template>
  <!-- <pre>
    {{ JSON.stringify(content, null, 2) }}
  </pre> -->
  <v-container class="fill-height" fluid>
    <v-row align="center" justify="center" class="text-center" style="min-height:60vh;">
      <v-col>
        <div class="audio-area" style="width:100%;" v-if="audioUrl">
          <audio ref="audioRef" :src="`${env.fileRoot}${param}/${audioUrl}`" controls style="width:100%;" />
        </div>
        <div v-for="imageUrl in content.image" class="image-area" style="margin-top:1rem;">
          <img :src="`${env.fileRoot}${param}/${imageUrl}`"
            style="width:100%; display:block; margin:0 auto;" />
        </div>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
// @ts-ignore -- use virtual content list (generated by plugin)
import { items } from 'virtual:content-list'
import env from './env';

const route = useRoute()
const param = computed<string>(() => (route.params.param as string) ?? 'test')
const content = computed(() => items[param.value] ?? { key: param.value, audio: [], image: [], video: [] })
const audioUrl = computed<string | undefined>(() => content.value.audio?.[0])
</script>

<style scoped>
.image-area {
  text-align: center;
}

.image-area img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 0 auto;
}
</style>
